name: retail_flow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  get_it: ^7.6.0
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.0
flutter:
  uses-material-design: true
